# Generated by Django 3.1.2 on 2020-10-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
